# Generated by Django 5.2.5 on 2025-08-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leetcode', models.IntegerField(default=0)),
                ('geeksforgeeks', models.IntegerField(default=0)),
                ('codingninjas', models.IntegerField(default=0)),
                ('others', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Coding Platform',
                'verbose_name_plural': 'Coding Platforms',
            },
        ),
    ]
